# Generated by Django 4.1 on 2022-08-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('county', '0006_remove_countymap_county_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('accuracy_score', models.FloatField()),
                ('accuracy_type', models.FloatField()),
                ('street', models.CharField(max_length=96)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('plus4', models.CharField(blank=True, max_length=5, null=True)),
                ('building_name', models.CharField(blank=True, max_length=64, null=True)),
                ('record_type_description', models.CharField(blank=True, max_length=32, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='county.county')),
            ],
        ),
    ]
