# Generated by Django 4.1 on 2022-08-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocode', '0002_alter_address_accuracy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='accuracy_type',
            field=models.CharField(max_length=64),
        ),
    ]
