# Generated by Django 4.0.6 on 2022-08-07 19:09

from django.db import migrations, models
import django.db.models.deletion
from datetime import date

class Migration(migrations.Migration):

    dependencies = [
        ('county', '0004_alter_county_geoid'),
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='name_title',
        ),
        migrations.AddField(
            model_name='voter',
            name='edition_date',
            field=models.DateField(default=date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='precinct_id_text',
            field=models.CharField(default='xxxxx', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailingaddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mailingaddress',
            name='address_line3',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mailingaddress',
            name='apt_no',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mailingaddress',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='mailingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mailingaddress',
            name='house_number',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='mailingaddress',
            name='street_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='residenceaddress',
            name='apt_no',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='residenceaddress',
            name='city',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='residenceaddress',
            name='street_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_changed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='voter',
            name='middle_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='name_suffix',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='OtherJurisdictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_district', models.CharField(blank=True, max_length=5, null=True)),
                ('land_lot', models.CharField(blank=True, max_length=5, null=True)),
                ('city_precinct_id', models.CharField(blank=True, max_length=5, null=True)),
                ('judicial_district', models.CharField(blank=True, max_length=4, null=True)),
                ('commission_district', models.CharField(blank=True, max_length=3, null=True)),
                ('school_district', models.CharField(blank=True, max_length=3, null=True)),
                ('county_districta_name', models.CharField(blank=True, max_length=5, null=True)),
                ('county_districta_value', models.CharField(blank=True, max_length=3, null=True)),
                ('county_districtb_name', models.CharField(blank=True, max_length=5, null=True)),
                ('county_districtb_value', models.CharField(blank=True, max_length=2, null=True)),
                ('municipal_name', models.CharField(blank=True, max_length=32, null=True)),
                ('municipal_code', models.CharField(blank=True, max_length=3, null=True)),
                ('ward_city_council_name', models.CharField(blank=True, max_length=5, null=True)),
                ('ward_city_council_code', models.CharField(blank=True, max_length=3, null=True)),
                ('city_school_district_name', models.CharField(blank=True, max_length=5, null=True)),
                ('city_school_district_value', models.CharField(blank=True, max_length=3, null=True)),
                ('district_combo', models.CharField(blank=True, max_length=3, null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.county')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.voter')),
            ],
        ),
    ]
