# Generated by Django 4.0.6 on 2022-08-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_remove_voter_name_title_voter_edition_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
