# Generated by Django 4.0.6 on 2022-08-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_alter_voter_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherjurisdictions',
            name='county_districtb_value',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
