# Generated by Django 4.0.6 on 2022-08-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0005_alter_otherjurisdictions_county_districtb_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residenceaddress',
            name='house_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
