# Generated by Django 4.0.6 on 2022-08-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0006_alter_residenceaddress_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingaddress',
            name='house_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
