# Generated by Django 4.0.6 on 2022-08-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0007_alter_mailingaddress_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mailingaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
