# Generated by Django 4.0.6 on 2022-08-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0009_alter_residenceaddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residenceaddress',
            name='house_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
    ]
