# Generated by Django 4.1 on 2022-08-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0010_alter_residenceaddress_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingaddress',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_address_of', to='voter.voter'),
        ),
        migrations.AlterField(
            model_name='residenceaddress',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residence_address_of', to='voter.voter'),
        ),
    ]
