# Generated by Django 4.0.6 on 2022-07-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_addressvoter_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CngMap',
        ),
        migrations.AlterModelOptions(
            name='addressvoter',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='blockgroupgeometry',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='children',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contestclass',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='countydetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='countymap',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='educationalattainment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='electionresultdetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='electionresults',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='electionresultsoverunder',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hsemap',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mailingaddress',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mailingaddressvoter',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medianhouseholdincome',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='precinctdetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='precinctsummary',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='residenceaddress',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='senmap',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='votercng',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='voterdemographics',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='voterhistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='voterhistorysummary',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='voterhse',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='votername',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='voterprecinct',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='voterscore',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='votersearch',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='votersen',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='voterstatus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vtdmap',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='worktraveltime',
            options={'managed': False},
        ),
    ]
