# Generated by Django 4.0.6 on 2022-07-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_delete_cngmap_alter_addressvoter_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SenMap',
        ),
    ]
