# Generated by Django 4.0.6 on 2022-07-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_delete_countymap_delete_hsemap_delete_voterhistory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectionResultDetails',
        ),
        migrations.DeleteModel(
            name='ElectionResults',
        ),
        migrations.DeleteModel(
            name='ElectionResultsOverUnder',
        ),
    ]
