# Generated by Django 4.0.6 on 2022-07-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_delete_electionresultdetails_delete_electionresults_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestClass',
        ),
        migrations.DeleteModel(
            name='CountyDetails',
        ),
    ]
