# Generated by Django 4.0.6 on 2022-07-30 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_delete_contestclass_delete_countydetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voterhse',
            options={},
        ),
    ]
