# Generated by Django 4.0.6 on 2022-07-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_alter_voterhse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voterhse',
            options={'managed': False},
        ),
    ]
