# Generated by Django 4.0.6 on 2022-08-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_voterhse_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoterDemographics',
        ),
        migrations.DeleteModel(
            name='VoterStatus',
        ),
    ]
