# Generated by Django 4.0.6 on 2022-08-10 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_delete_voterdemographics_delete_voterstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressVoter',
        ),
        migrations.DeleteModel(
            name='MailingAddress',
        ),
        migrations.DeleteModel(
            name='MailingAddressVoter',
        ),
        migrations.DeleteModel(
            name='ResidenceAddress',
        ),
        migrations.DeleteModel(
            name='VoterCng',
        ),
        migrations.DeleteModel(
            name='VoterHse',
        ),
        migrations.DeleteModel(
            name='VoterName',
        ),
        migrations.DeleteModel(
            name='VoterSen',
        ),
    ]
