# Generated by Django 4.1 on 2022-08-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_delete_addressvoter_delete_mailingaddress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrecinctDetails',
        ),
    ]
