# Generated by Django 4.0.6 on 2022-07-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoterHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('district', models.TextField()),
                ('population', models.IntegerField()),
                ('ideal_value', models.FloatField()),
                ('geometry_wkb', models.TextField()),
                ('center_wkb', models.TextField()),
                ('voter_id', models.TextField()),
                ('year', models.IntegerField()),
                ('date', models.TextField()),
                ('type', models.TextField()),
                ('party', models.TextField(blank=True, null=True)),
                ('county_id', models.TextField()),
                ('absentee', models.IntegerField()),
                ('provisional', models.IntegerField()),
                ('supplemental', models.IntegerField()),
            ],
            options={
                'db_table': 'voter_history',
            },
        ),
    ]
