# Generated by Django 4.0.6 on 2022-07-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterhistory',
            name='area',
        ),
        migrations.RemoveField(
            model_name='voterhistory',
            name='center_wkb',
        ),
        migrations.RemoveField(
            model_name='voterhistory',
            name='district',
        ),
        migrations.RemoveField(
            model_name='voterhistory',
            name='geometry_wkb',
        ),
        migrations.RemoveField(
            model_name='voterhistory',
            name='ideal_value',
        ),
        migrations.RemoveField(
            model_name='voterhistory',
            name='population',
        ),
        migrations.AlterField(
            model_name='voterhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
