# Generated by Django 4.0.6 on 2022-07-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_history', '0002_remove_voterhistory_area_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voterhistory',
            index=models.Index(fields=['voter_id'], name='voter_histo_voter_i_579fce_idx'),
        ),
        migrations.AddIndex(
            model_name='voterhistory',
            index=models.Index(fields=['year'], name='voter_histo_year_b9764f_idx'),
        ),
        migrations.AddIndex(
            model_name='voterhistory',
            index=models.Index(fields=['date'], name='voter_histo_date_eef1f1_idx'),
        ),
    ]
