# Generated by Django 4.0.6 on 2022-07-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_history', '0003_voterhistory_voter_histo_voter_i_579fce_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterhistory',
            old_name='county_id',
            new_name='county_code',
        ),
    ]
