# Generated by Django 4.0.6 on 2022-07-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_history', '0004_rename_county_id_voterhistory_county_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='voterhistory',
            name='voter_histo_year_b9764f_idx',
        ),
        migrations.RemoveIndex(
            model_name='voterhistory',
            name='voter_histo_date_eef1f1_idx',
        ),
        migrations.RenameField(
            model_name='voterhistory',
            old_name='date',
            new_name='h_date',
        ),
        migrations.RenameField(
            model_name='voterhistory',
            old_name='year',
            new_name='h_year',
        ),
        migrations.AddIndex(
            model_name='voterhistory',
            index=models.Index(fields=['h_year'], name='voter_histo_h_year_c4992f_idx'),
        ),
        migrations.AddIndex(
            model_name='voterhistory',
            index=models.Index(fields=['h_date'], name='voter_histo_h_date_40ce56_idx'),
        ),
    ]
