# Generated by Django 4.0.6 on 2022-07-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_history', '0005_remove_voterhistory_voter_histo_year_b9764f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterhistory',
            name='absentee',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voterhistory',
            name='provisional',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voterhistory',
            name='supplemental',
            field=models.BooleanField(),
        ),
    ]
