# Generated by Django 4.0.6 on 2022-07-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VtdMap',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('precinct_id', models.TextField()),
                ('precinct_name', models.TextField()),
                ('county_code', models.TextField()),
                ('county_fips', models.TextField()),
                ('county_name', models.TextField()),
                ('geometry_wkb', models.TextField()),
                ('center_wkb', models.TextField()),
            ],
            options={
                'db_table': 'vtd_map',
                'managed': False,
            },
        ),
    ]
