# Generated by Django 4.0.6 on 2022-07-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HseMap',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('district', models.TextField()),
                ('population', models.IntegerField()),
                ('ideal_value', models.FloatField()),
                ('geometry_wkb', models.TextField()),
                ('center_wkb', models.TextField()),
            ],
            options={
                'db_table': 'hse_map',
                'managed': False,
            },
        ),
    ]
