# Generated by Django 4.0.6 on 2022-08-06 18:26

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('county', '0004_alter_county_geoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecinctEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
                ('path', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrecinctMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinct_id', models.TextField()),
                ('geometry_wkb', models.TextField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.county')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precinct.precinctedition')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.BaseMap),
        ),
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinct_id', models.TextField()),
                ('precinct_name', models.TextField(blank=True, null=True)),
                ('aka', models.TextField(blank=True, null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.county')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precinct.precinctedition')),
                ('precinct_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precinct.precinctmap')),
            ],
        ),
    ]
