# Generated by Django 4.1 on 2022-08-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0006_remove_countymap_county_code'),
        ('precinct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precinctmap',
            old_name='precinct_id',
            new_name='precinct_short_name',
        ),
        migrations.AlterField(
            model_name='precinct',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precincts_of', to='county.county'),
        ),
    ]
