# Generated by Django 4.1 on 2022-08-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precinct', '0002_rename_precinct_id_precinctmap_precinct_short_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precinct',
            name='precinct_map',
        ),
    ]
