# Generated by Django 4.1 on 2022-08-14 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precinct', '0003_remove_precinct_precinct_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='precinctmap',
            name='precinct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps_of', to='precinct.precinct'),
        ),
    ]
