# Generated by Django 4.1 on 2022-08-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precinct', '0005_alter_precinctmap_precinct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precinctmap',
            name='precinct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_of', to='precinct.precinct'),
        ),
    ]
