# Generated by Django 4.0.6 on 2022-08-06 15:50

import core.base_fig
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.CharField(max_length=3)),
                ('county_fips', models.CharField(max_length=3)),
                ('county_name', models.TextField()),
                ('state_fips', models.CharField(max_length=2)),
                ('geoid', models.CharField(max_length=12)),
                ('aland', models.IntegerField()),
                ('awater', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.base_fig.BaseMap),
        ),
    ]
