# Generated by Django 4.0.6 on 2022-08-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='aland',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='county',
            name='awater',
            field=models.FloatField(),
        ),
    ]
