# Generated by Django 4.0.6 on 2022-08-06 16:03

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0002_alter_county_aland_alter_county_awater'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.CharField(max_length=3)),
                ('geometry_wkb', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.BaseMap),
        ),
        migrations.AddField(
            model_name='county',
            name='county_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='county.countymap'),
        ),
    ]
