# Generated by Django 4.0.6 on 2022-07-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockGroupMap',
            fields=[
                ('geoid', models.TextField(primary_key=True, serialize=False)),
                ('state_fips', models.TextField()),
                ('county_fips', models.TextField()),
                ('tract', models.TextField()),
                ('blockgroup', models.TextField()),
                ('geometry_wkb', models.TextField()),
                ('center_wkb', models.TextField()),
            ],
            options={
                'db_table': 'blockgroup_map',
                'managed': False,
            },
        ),
    ]
