# Generated by Django 4.0.6 on 2022-07-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockgroup_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockgroupmap',
            options={},
        ),
    ]
