# Generated by Django 4.0.6 on 2022-07-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockgroup_map', '0002_alter_blockgroupmap_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockgroupmap',
            name='geoid',
            field=models.TextField(),
        ),

        migrations.AddField(
            model_name='blockgroupmap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
