# Generated by Django 4.0.6 on 2022-07-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockgroup_map', '0003_blockgroupmap_id_alter_blockgroupmap_geoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockgroupmap',
            name='blockgroup',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='blockgroupmap',
            name='county_fips',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='blockgroupmap',
            name='geoid',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='blockgroupmap',
            name='state_fips',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='blockgroupmap',
            name='tract',
            field=models.CharField(max_length=6),
        ),
        migrations.AddIndex(
            model_name='blockgroupmap',
            index=models.Index(fields=['county_fips'], name='blockgroup__county__5cde77_idx'),
        ),
    ]
