# Generated by Django 4.0.6 on 2022-07-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountyDetails',
            fields=[
                ('county_code', models.TextField(primary_key=True, serialize=False)),
                ('county_fips', models.TextField()),
                ('county_name', models.TextField()),
            ],
            options={
                'db_table': 'county_details',
                'managed': False,
            },
        ),
    ]
