# Generated by Django 4.0.6 on 2022-07-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('county_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countydetails',
            options={},
        ),
    ]
