# Generated by Django 4.0.6 on 2022-07-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county_details', '0002_alter_countydetails_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countydetails',
            name='county_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='countydetails',
            name='county_fips',
            field=models.CharField(max_length=3),
        ),
        migrations.AddField(
            model_name='countydetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
